name: npm audit

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.TOKEN }}
          issue_labels: vulnerability,test
          dedupe_issues: true
